/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZustandCounterImport } from './routes/zustand-counter'
import { Route as VanillaCounterImport } from './routes/vanilla-counter'
import { Route as ReduxTodosImport } from './routes/redux-todos'
import { Route as ReduxCounterImport } from './routes/redux-counter'
import { Route as IndexImport } from './routes/index'
import { Route as TodosTsqueryIndexImport } from './routes/todos-tsquery/index'
import { Route as TodosTsqueryTodoIdImport } from './routes/todos-tsquery/$todoId'

// Create/Update Routes

const ZustandCounterRoute = ZustandCounterImport.update({
  id: '/zustand-counter',
  path: '/zustand-counter',
  getParentRoute: () => rootRoute,
} as any)

const VanillaCounterRoute = VanillaCounterImport.update({
  id: '/vanilla-counter',
  path: '/vanilla-counter',
  getParentRoute: () => rootRoute,
} as any)

const ReduxTodosRoute = ReduxTodosImport.update({
  id: '/redux-todos',
  path: '/redux-todos',
  getParentRoute: () => rootRoute,
} as any)

const ReduxCounterRoute = ReduxCounterImport.update({
  id: '/redux-counter',
  path: '/redux-counter',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodosTsqueryIndexRoute = TodosTsqueryIndexImport.update({
  id: '/todos-tsquery/',
  path: '/todos-tsquery/',
  getParentRoute: () => rootRoute,
} as any)

const TodosTsqueryTodoIdRoute = TodosTsqueryTodoIdImport.update({
  id: '/todos-tsquery/$todoId',
  path: '/todos-tsquery/$todoId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/redux-counter': {
      id: '/redux-counter'
      path: '/redux-counter'
      fullPath: '/redux-counter'
      preLoaderRoute: typeof ReduxCounterImport
      parentRoute: typeof rootRoute
    }
    '/redux-todos': {
      id: '/redux-todos'
      path: '/redux-todos'
      fullPath: '/redux-todos'
      preLoaderRoute: typeof ReduxTodosImport
      parentRoute: typeof rootRoute
    }
    '/vanilla-counter': {
      id: '/vanilla-counter'
      path: '/vanilla-counter'
      fullPath: '/vanilla-counter'
      preLoaderRoute: typeof VanillaCounterImport
      parentRoute: typeof rootRoute
    }
    '/zustand-counter': {
      id: '/zustand-counter'
      path: '/zustand-counter'
      fullPath: '/zustand-counter'
      preLoaderRoute: typeof ZustandCounterImport
      parentRoute: typeof rootRoute
    }
    '/todos-tsquery/$todoId': {
      id: '/todos-tsquery/$todoId'
      path: '/todos-tsquery/$todoId'
      fullPath: '/todos-tsquery/$todoId'
      preLoaderRoute: typeof TodosTsqueryTodoIdImport
      parentRoute: typeof rootRoute
    }
    '/todos-tsquery/': {
      id: '/todos-tsquery/'
      path: '/todos-tsquery'
      fullPath: '/todos-tsquery'
      preLoaderRoute: typeof TodosTsqueryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redux-counter': typeof ReduxCounterRoute
  '/redux-todos': typeof ReduxTodosRoute
  '/vanilla-counter': typeof VanillaCounterRoute
  '/zustand-counter': typeof ZustandCounterRoute
  '/todos-tsquery/$todoId': typeof TodosTsqueryTodoIdRoute
  '/todos-tsquery': typeof TodosTsqueryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redux-counter': typeof ReduxCounterRoute
  '/redux-todos': typeof ReduxTodosRoute
  '/vanilla-counter': typeof VanillaCounterRoute
  '/zustand-counter': typeof ZustandCounterRoute
  '/todos-tsquery/$todoId': typeof TodosTsqueryTodoIdRoute
  '/todos-tsquery': typeof TodosTsqueryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/redux-counter': typeof ReduxCounterRoute
  '/redux-todos': typeof ReduxTodosRoute
  '/vanilla-counter': typeof VanillaCounterRoute
  '/zustand-counter': typeof ZustandCounterRoute
  '/todos-tsquery/$todoId': typeof TodosTsqueryTodoIdRoute
  '/todos-tsquery/': typeof TodosTsqueryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/redux-counter'
    | '/redux-todos'
    | '/vanilla-counter'
    | '/zustand-counter'
    | '/todos-tsquery/$todoId'
    | '/todos-tsquery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redux-counter'
    | '/redux-todos'
    | '/vanilla-counter'
    | '/zustand-counter'
    | '/todos-tsquery/$todoId'
    | '/todos-tsquery'
  id:
    | '__root__'
    | '/'
    | '/redux-counter'
    | '/redux-todos'
    | '/vanilla-counter'
    | '/zustand-counter'
    | '/todos-tsquery/$todoId'
    | '/todos-tsquery/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReduxCounterRoute: typeof ReduxCounterRoute
  ReduxTodosRoute: typeof ReduxTodosRoute
  VanillaCounterRoute: typeof VanillaCounterRoute
  ZustandCounterRoute: typeof ZustandCounterRoute
  TodosTsqueryTodoIdRoute: typeof TodosTsqueryTodoIdRoute
  TodosTsqueryIndexRoute: typeof TodosTsqueryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReduxCounterRoute: ReduxCounterRoute,
  ReduxTodosRoute: ReduxTodosRoute,
  VanillaCounterRoute: VanillaCounterRoute,
  ZustandCounterRoute: ZustandCounterRoute,
  TodosTsqueryTodoIdRoute: TodosTsqueryTodoIdRoute,
  TodosTsqueryIndexRoute: TodosTsqueryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/redux-counter",
        "/redux-todos",
        "/vanilla-counter",
        "/zustand-counter",
        "/todos-tsquery/$todoId",
        "/todos-tsquery/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/redux-counter": {
      "filePath": "redux-counter.tsx"
    },
    "/redux-todos": {
      "filePath": "redux-todos.tsx"
    },
    "/vanilla-counter": {
      "filePath": "vanilla-counter.tsx"
    },
    "/zustand-counter": {
      "filePath": "zustand-counter.tsx"
    },
    "/todos-tsquery/$todoId": {
      "filePath": "todos-tsquery/$todoId.tsx"
    },
    "/todos-tsquery/": {
      "filePath": "todos-tsquery/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
